<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="itrs_appserver.DataBaseControllerTest" tests="19" skipped="0" failures="0" errors="0" timestamp="2016-02-04T10:08:49" hostname="ITRSLP043" time="0.325">
  <properties/>
  <testcase name="createInValidDeviceFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.019"/>
  <testcase name="removeCustomDataviewTest" classname="itrs_appserver.DataBaseControllerTest" time="0.038"/>
  <testcase name="verifyStoredDeviceFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.006"/>
  <testcase name="logoutDeviceFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.007"/>
  <testcase name="getUserDataviewListFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.008"/>
  <testcase name="checkValidDomainFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.013"/>
  <testcase name="verifyStoredDeviceTest" classname="itrs_appserver.DataBaseControllerTest" time="0.052"/>
  <testcase name="sqlConnectFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.001"/>
  <testcase name="getLivePathsTest" classname="itrs_appserver.DataBaseControllerTest" time="0.033"/>
  <testcase name="removeCustomDataviewFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.008"/>
  <testcase name="addCustomDataViewFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.008"/>
  <testcase name="userCheckFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.008"/>
  <testcase name="checkDeviceExistenceFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.008"/>
  <testcase name="getUserDataviewListTest" classname="itrs_appserver.DataBaseControllerTest" time="0.031"/>
  <testcase name="getLivePathsFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.011"/>
  <testcase name="execCustomFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.023"/>
  <testcase name="loginDeviceFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.007"/>
  <testcase name="createUserFailTest" classname="itrs_appserver.DataBaseControllerTest" time="0.006"/>
  <testcase name="getLiveDevicesTest" classname="itrs_appserver.DataBaseControllerTest" time="0.025"/>
  <system-out><![CDATA[10:08:49.358 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  Remoting - Starting remoting
10:08:49.359 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  Remoting - Starting remoting
10:08:49.363 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  Remoting - Starting remoting
10:08:49.631 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:21191]
10:08:49.633 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:21192]
10:08:49.636 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-2] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://OpenAccessApiClient-UnknownDevBuild@192.168.10.207:21190]
[testb6]
[testc6]
[testa6]
10:08:49.733 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-15] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
10:08:49.733 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-3] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
10:08:49.734 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-7] INFO  c.itrsgroup.actor.MessageDispatcher - Attempting to connect to remote service at [192.168.220.54:2551] 1 time(s)
10:08:50.005 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
10:08:50.006 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
10:08:50.011 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-15] INFO  akka.contrib.pattern.ClusterClient - Connected to [akka.tcp://ClusterSystem@192.168.220.54:2551/user/receptionist]
10:08:50.082 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
10:08:50.082 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-5] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
10:08:50.083 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] INFO  c.itrsgroup.actor.MessageDispatcher - Authenticating with remote service [/user/frontEnd] at [192.168.220.54:2551]
10:08:50.353 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-16] INFO  c.itrsgroup.actor.MessageDispatcher - Successfully connected to remote service [akka.tcp://ClusterSystem@192.168.220.54:2551/user/frontEnd]
10:08:50.356 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-16] INFO  c.itrsgroup.actor.MessageDispatcher - Forwarding Subscription op to cluster frontend: Subscribe(ModelSub(testa6/rows/row[wild(@name,"*")]/cell,Set(),LIST,),None)
10:08:50.411 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-18] INFO  c.itrsgroup.actor.MessageDispatcher - Successfully connected to remote service [akka.tcp://ClusterSystem@192.168.220.54:2551/user/frontEnd]
10:08:50.412 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-18] INFO  c.itrsgroup.actor.MessageDispatcher - Forwarding Subscription op to cluster frontend: Subscribe(ModelSub(testc6/rows/row[wild(@name,"*")]/cell,Set(),LIST,),None)
10:08:50.511 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-7] ERROR c.itrsgroup.actor.DataSetClientActor - Exception calling error callback
java.lang.RuntimeException: null
	at geneos_notification.thread_operations.ThreadInstance$2.error(ThreadInstance.java:100) ~[main/:na]
	at com.itrsgroup.actor.ClientActor$$anonfun$1.apply$mcV$sp(ClientActor.scala:143) ~[geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor$$anonfun$1.apply(ClientActor.scala:143) ~[geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor$$anonfun$1.apply(ClientActor.scala:143) ~[geneos-openaccess-client.jar:2.0.1]
	at scala.util.Try$.apply(Try.scala:191) ~[geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor.fireError(ClientActor.scala:143) [geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor$$anonfun$receive$1.applyOrElse(ClientActor.scala:84) [geneos-openaccess-client.jar:2.0.1]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [geneos-openaccess-client.jar:2.0.1]
	at com.itrsgroup.actor.ClientActor.aroundReceive(ClientActor.scala:38) [geneos-openaccess-client.jar:2.0.1]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [geneos-openaccess-client.jar:2.0.1]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [geneos-openaccess-client.jar:2.0.1]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [geneos-openaccess-client.jar:2.0.1]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [geneos-openaccess-client.jar:2.0.1]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [geneos-openaccess-client.jar:2.0.1]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [geneos-openaccess-client.jar:2.0.1]
]]></system-out>
  <system-err><![CDATA[Feb 04, 2016 10:08:49 AM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testb6
Feb 04, 2016 10:08:49 AM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testc6
Feb 04, 2016 10:08:49 AM geneos_notification.loggers.LogObject doLog
INFO: Thread xpath exection for path : testa6
Feb 04, 2016 10:08:50 AM geneos_notification.loggers.LogObject doLog
SEVERE: [T-ERROR]Error retrieving DataSet: java.lang.Exception: Invalid step in path: testa6
Feb 04, 2016 10:08:50 AM geneos_notification.loggers.LogObject doLog
INFO: [T-INFO]Thread Execution successful
Feb 04, 2016 10:08:50 AM geneos_notification.loggers.LogObject doLog
WARNING: [T-WARNING]OpenAccess null response due to multiple reloads, this is handled and expected.
]]></system-err>
</testsuite>
